project_id = "zrdywdregcrykmbiytvl"

[functions.chat_dory]
verify_jwt = false

[functions.tts_dory]
verify_jwt = false

[functions.stt_chat]
verify_jwt = false

[functions.voice_chat_dory]
verify_jwt = false

[functions.generate_image]
verify_jwt = false

[functions.follow-dory]
verify_jwt = false

[functions.health-check]
verify_jwt = false